### ISSUE TITLE
Option to convert other path attributes to text elements

### ISSUE THREAD

**Issue by whiplashoo** [whiplashoo/ids_to_text_inkscape#4]
Currently the extension grabs the path ids and converts them to text elements inside the paths. Allow the user to do the same for other path attributes as well, like fill, stroke, stroke-width, x, y, etc.

**Comment by SaibotMagd** [comment]
> Currently the extension grabs the path ids and converts them to text elements inside the paths. Allow the user to do the same for other path attributes as well, like fill, stroke, stroke-width, x, y, etc.

For me the "label" attribute would be important. It would also be great to use grouped notes

**Comment by whiplashoo** [comment]
@SaibotMagd Yes, the 'label' attribute can be one of the options as well.

By grouped notes, what do you mean?

**Comment by whiplashoo** [comment]
You can now select which attribute to extract from the paths. It can be one of:

- `id`
- `label`
- `fill`
- `stroke`
- `width`
- `height`
