### ISSUE TITLE
Option to group text to path

### ISSUE THREAD

**Issue by amunizp** [whiplashoo/ids_to_text_inkscape#5]
This tool is exactly what I was looking for. It would help greatly if there was an option in which the text generated could be grouped with the path it came from.

Use case: local community fair is looking to position stalls on a map. Each stall is represented by a numbered box.

**Comment by whiplashoo** [comment]
Closed! There is now a checkbox you can use to set if you want the generated `<text>` elements to be grouped with their paths.
