### ISSUE TITLE
Compatibiliy with Inkscape 1.3.2 and Windows 11?

### ISSUE THREAD

**Issue by ericnutsch** [whiplashoo/ids_to_text_inkscape#6]
From the extension manager it seems the "Install Package" button is greyed out. I see in the green tags that only v1.2 is shown so perhaps that is blocking it.
![image](https://github.com/whiplashoo/ids_to_text_inkscape/assets/8228217/c57f06e4-164b-49fe-ac42-cadc27d4260e)

I also tried manually installing by pasting in to the extensions folder and restarting inkscape but all i get "Orphan Extensions" showing up in the extension manager.
![image](https://github.com/whiplashoo/ids_to_text_inkscape/assets/8228217/7378613e-27f4-4820-a76f-dd5a62f9da66)

(after removing the files above) I also tried the manual file selection button from inside the extension manager gui. I tried selecting the ids_to_text.py file, clicking open and tried selecting the ids_to_text.inx file and clicking open but nothing happened. After I close the extension manager i get a long list of errors ending with the following.
![image](https://github.com/whiplashoo/ids_to_text_inkscape/assets/8228217/7fa8f2da-78b0-4e61-82e4-f4f4b74640bc)

Thanks!

**Comment by whiplashoo** [comment]
Hey, can you try again? I updated the tags in the extension listing to also include 1.3, and I was able to install from the Extension manager on macOS. I will check on Windows soon, but it should 99% work  there too.

**Comment by ericnutsch** [comment]
@whiplashoo, Awesome! That took care of it. I installed it from the extension manager gui. Thanks!
